### ISSUE TITLE
plumber in Suggests?

### ISSUE THREAD

**Issue by jonthegeek** [rstudio/vetiver-r#136]
I understand if this is a route you don't want to go down, but there are situations where deploying *without* plumber makes sense, such as on AWS Lambda (see #128). It would be nice to avoid installing extra things in that case, and {plumber} comes with a number of dependencies, including {sodium}, which has a `libsodium` system requirement (and thus adds another step to the process).

Would you consider moving {plumber} to Suggests for {vetiver}, and only adding it to the `vetiver_renv.lock` when it makes sense to do so (ie, for almost every deployment path other than Lambda, probably)?

It probably isn't a HUGE issue, but I can imagine getting to a point where we want to shave every little thing out of that container that we can.

**Comment by juliasilge** [comment]
Yep, this makes sense. We can move plumber to Suggests and use `rlang::check_installed("plumber")` in the appropriate places.

**Comment by juliasilge** [comment]
I did work on this in #140 this week, but it turns out most of the vetiver testing strategy doesn't work without plumber in Imports. (We have a testing strategy where a REST API runs in one session and http calls are made from another session.)

Moving plumber to Suggests would take more work than I initially thought, so let's keep things as is for now but keep this issue open to collect feedback for prioritization.
